[package]
name = "poolgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version="3.2.23", features=["derive"]}
nalgebra = "0.32.1"
statrs = "0.16.0"
argmin = "0.8.1"
argmin-math = "0.3.0"
finitediff = "0.1.4"
# argmin_testfunctions = "*"

# argmin-math = { version = "0.3.0", default-features = false, features = ["primitives"]}
# argmin_testfunctions = "*"
# serde = "1.0"
# ndarray = { version = "0.15", features = ["serde-1"] }
# finitediff = { version = "0.1.4", features = ["ndarray"] }
# 
# anyhow = "1.0"
# instant = {version = "0.1" }
# paste = "1"
# num-traits = { version = "0.2" }
# rand = { version = "0.8.5" }
# rand_xoshiro = { version = "0.6.0" }
# thiserror = "1.0"

# nelder_mead = { git = "https://github.com/JD557/nelder-mead.rs.git", branch = "master" }
