name: 🚀
on:
  push:
    branches:
      - main
jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - name: Build | Compile
        run: cargo check
  test:
    name: Test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        rust:
          - stable
          - beta
          - nightly
    runs-on: ${{ matrix.os }}
    needs: [compile]
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: ${{ matrix.rust }}
      - name: Build | Compile
        run: | 
          echo "###############################################################"
          echo "Using the minimum number of parameters, i.e. use defula values:"
          cargo run -- pileup2sync -f ./tests/test.pileup --pool-names ./tests/test_names.txt
          cargo run -- pileup2sync -f ./tests/test.pileup --pool-names ./tests/test_names.txt --n-threads 2 --min-quality 0.0001
          cargo run -- pileup2sync -f ./tests/test.pileup --pool-names ./tests/test_names.txt --n-threads 2 --min-quality 0.0001 --min-coverage 10
          cargo run -- pileup2sync -f ./tests/test.pileup --pool-names ./tests/test_names.txt --n-threads 2 --min-quality 0.0001 --min-coverage 10 --min-allele-frequency 0.01
          cargo run -- fisher_exact_test -f ./tests/test.sync --n-threads 2
          cargo run -- fisher_exact_test -f ./tests/test.sync --n-threads 2 --min-coverage 10 --min-allele-frequency 0.01
          cargo run -- chisq_test -f ./tests/test.sync --n-threads 2
          cargo run -- chisq_test -f ./tests/test.sync --n-threads 2 --min-coverage 10 --min-allele-frequency 0.01
          # cargo run -- pearson_corr -f ./tests/test.sync  --phen-fname ./tests/test.csv --phen-delim , --phen-name-col 0 --phen-value-col 1,2  --n-threads 2
          # cargo run -- pearson_corr -f ./tests/test.syncx --phen-fname ./tests/test.csv --phen-delim , --phen-name-col 0 --phen-value-col 1,2  --n-threads 2
          # cargo run -- ols_iter -f ./tests/test.sync  --phen-fname ./tests/test.csv --phen-delim , --phen-name-col 0 --phen-value-col 1,2  --n-threads 2
          # cargo run -- ols_iter -f ./tests/test.syncx --phen-fname ./tests/test.csv --phen-delim , --phen-name-col 0 --phen-value-col 1,2  --n-threads 2
          echo "###############################################################"
          echo "Clean-up:"
          rm ./tests/test-*
          
