name: 🚀
on:
  push:
    branches:
      - main
jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - name: Build | Compile
        run: cargo check
  test:
    name: Test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        rust:
          - stable
          - beta
          - nightly
    runs-on: ${{ matrix.os }}
    needs: [compile]
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: ${{ matrix.rust }}
      - name: Build | Compile
        run: | 
          cargo run -- -f ./tests/test.pileup -p ./tests/test_names.txt
          cargo run -- -f ./tests/test.pileup -p ./tests/test_names.txt --n-threads 2 --min-cov 2
          cargo run -- -f ./tests/test.pileup -p ./tests/test_names.txt --file-format syncf --n-threads 2 --min-cov 2
          cargo run -- -f ./tests/test.pileup -p ./tests/test_names.txt --file-format syncx --n-threads 2 --min-cov 2
