name: 🚀
on:
  push:
    branches:
      - main
jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - name: Build | Compile
        run: cargo check
  test:
    name: Test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          # - macOS-latest
        rust:
          - stable
          # - beta
          # - nightly
    runs-on: ${{ matrix.os }}
    needs: [compile]
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: ${{ matrix.rust }}
      - name: Tests | Rust
        run: cargo test
      - name: Build | Compile | Test on test data
        run: | 
          cargo run -- pileup2sync -f ./tests/test.pileup -p ./tests/test.csv
          cargo run -- pileup2sync -f ./tests/test.pileup -p ./tests/test.csv --n-threads 2 --min-quality 0.0001
          cargo run -- pileup2sync -f ./tests/test.pileup -p ./tests/test.csv --n-threads 2 --min-quality 0.0001 --min-coverage 10
          cargo run -- pileup2sync -f ./tests/test.pileup -p ./tests/test.csv --n-threads 2 --min-quality 0.0001 --min-coverage 10 --min-allele-frequency 0.01
          cargo run -- fisher_exact_test -f ./tests/test.sync -p ./tests/test.csv --n-threads 2
          cargo run -- fisher_exact_test -f ./tests/test.sync -p ./tests/test.csv --n-threads 2 --min-coverage 10 --min-allele-frequency 0.01
          cargo run -- chisq_test -f ./tests/test.sync -p ./tests/test.csv --n-threads 2
          cargo run -- chisq_test -f ./tests/test.sync -p ./tests/test.csv --n-threads 2 --min-coverage 10 --min-allele-frequency 0.01
          cargo run -- pearson_corr -f ./tests/test.sync -p ./tests/test.csv --phen-delim , --phen-name-col 0 --phen-value-col 2,3  --n-threads 2
          cargo run -- pearson_corr -f ./tests/test.sync -p ./tests/test.csv --phen-delim , --phen-name-col 0 --phen-value-col 2,3  --n-threads 2 --min-coverage 10 --min-allele-frequency 0.01
          cargo run -- ols_iter -f ./tests/test.sync -p ./tests/test.csv --phen-delim , --phen-name-col 0 --phen-value-col 2,3  --n-threads 2
          cargo run -- ols_iter -f ./tests/test.sync -p ./tests/test.csv --phen-delim , --phen-name-col 0 --phen-value-col 2,3  --n-threads 2 --min-coverage 10 --min-allele-frequency 0.01
          cargo run -- mle_iter -f ./tests/test.sync -p ./tests/test.csv --phen-delim , --phen-name-col 0 --phen-value-col 2,3  --n-threads 2
          cargo run -- mle_iter -f ./tests/test.sync -p ./tests/test.csv --phen-delim , --phen-name-col 0 --phen-value-col 2,3  --n-threads 2 --min-coverage 10 --min-allele-frequency 0.01
          cargo run -- gwalpha  -f ./tests/test.sync -p ./tests/test.py --n-threads 2 --gwalpha-method LS
          cargo run -- gwalpha  -f ./tests/test.sync -p ./tests/test.py --n-threads 2 --gwalpha-method ML
          cargo run -- sync2csv -f ./tests/test.sync -p ./tests/test.csv --phen-delim , --phen-name-col 0 --phen-value-col 2,3  --n-threads 2
          cargo run -- sync2csv -f ./tests/test.sync -p ./tests/test.csv --phen-delim , --phen-name-col 0 --phen-value-col 2,3  --n-threads 2 --keep-p-minus-1
          cargo run -- fst -f ./tests/test.sync -p ./tests/test.csv --phen-delim , --phen-name-col 0 --phen-value-col 2,3  --n-threads 2
          cargo run -- xpclr -f ./tests/test.sync -p ./tests/test.csv --phen-delim , --phen-name-col 0 --phen-value-col 2,3 --window-size-bp 100000 --selection-coefficient-min 0.5 --selection-coefficient-max 0.5 --selection-coefficient-n-steps 1 --recombination-rate-min 1.0e-5 --recombination-rate-max 1.0e-5 --recombination-rate-n-steps 1 --n-threads 2
          cargo run -- heterozygosity -f ./tests/test.sync -p ./tests/test.csv --phen-delim , --phen-name-col 0 --phen-value-col 2,3  --n-threads 2
          # cargo run -- genomic_prediction_cross_validation -f ./tests/test_MORE_POOLS.sync -p ./tests/test_MORE_POOLS.csv --phen-delim , --phen-name-col 0 --phen-value-col 2,3  --n-threads 2