name: 🚀
on:
  push:
    branches:
      - main
jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - name: Build | Compile
        run: cargo check
  test:
    name: Test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        rust:
          - stable
          - beta
          - nightly
    runs-on: ${{ matrix.os }}
    needs: [compile]
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: ${{ matrix.rust }}
      - name: Build | Compile
        run: | 
          echo "###############################################################"
          echo "Using the minimum number of parameters, i.e. use defula values:"
          cargo run -- pileup2sync -f ./tests/test.pileup --pool-names ./tests/test_names.txt
          cargo run -- sync2syncx -f ./tests/test.sync
          echo "###############################################################"
          echo "Run with multiple custom parameters:"
          cargo run -- pileup2sync -f ./tests/test.pileup                   -o ./tests/test-pileup2sync_default.sync  --pool-names ./tests/test_names.txt
          cargo run -- pileup2sync -f ./tests/test.pileup                   -o ./tests/test-pileup2sync_mincov2.sync  --pool-names ./tests/test_names.txt --n-threads 2 --min-cov 2
          cargo run -- pileup2sync -f ./tests/test.pileup                   -o ./tests/test-pileup2sync_mincov2.syncx --pool-names ./tests/test_names.txt --file-format syncx --n-threads 2 --min-cov 2
          cargo run -- sync2syncx  -f ./tests/test-pileup2sync_default.sync -o ./tests/test-pileup2sync_default_sync2syncx.syncx --n-threads 2 --min-cov 2
          cargo run -- sync2syncx  -f ./tests/test-pileup2sync_mincov2.sync -o ./tests/test-pileup2sync_mincov2_sync2syncx.syncx --n-threads 2 --min-cov 2
          # d1=$(diff ./tests/test-pileup2sync_default_sync2syncx.syncx ./tests/test-pileup2sync_mincov2.syncx | wc -l)
          # d2=$(diff ./tests/test-pileup2sync_default_sync2syncx.syncx ./tests/test-pileup2sync_mincov2_sync2syncx.syncx | wc -l)
          # if [ $d1 -gt 0 ]
          # then
          #   exit 1
          # fi
          # if [ $d2 -gt 0 ]
          # then
          #   exit 2
          # fi
          echo "###############################################################"
          echo "More tests:"
          cargo run -- load -f ./tests/test.sync
          cargo run -- load -f ./tests/test.syncx
